parameters:
#    op_todo_app.example.class: OP\TodoAppBundle\Example

services:
#    op_todo_app.example:
#        class: %op_todo_app.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
